version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_DB: libsys
      POSTGRES_USER: libsys_user
      POSTGRES_PASSWORD: welcome2025
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  library-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/libsys
      SPRING_DATASOURCE_USERNAME: libsys_user
      SPRING_DATASOURCE_PASSWORD: welcome2025
    depends_on:
      - postgres

volumes:
  pgdata:
