apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  POSTGRES_DATABASE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL2xpYnN5cw==     # Base64 encoded 'library'
  POSTGRES_USER: bGlic3lzX3VzZXI=            # Base64 encoded 'libsys_user'
  POSTGRES_PASSWORD: d2VsY29tZTIwMjU=   # Base64 encoded 'password'
