# application.yaml (base config)
spring:
  datasource:
    url: jdbc:postgresql://db:5432/librarydb
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
