apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
   POSTGRES_DATABASE_URL: bGlicmFyeQ==    # Base64 encoded 'library'
   POSTGRES_USER: YWRtaW4=            # Base64 encoded 'admin'
   POSTGRES_PASSWORD: cGFzc3dvcmQ=    # Base64 encoded 'password'
   POSTGRES_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # Base64 encoded 'rootpassword'